package foto;


import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konkesiAPP.Session;
import konkesiAPP.koneksi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    String Tanggal;
    private DefaultTableModel model;
    
    public void grandtotal(){
        int jumlahbaris = jTable1.getRowCount();
        int grandtotal = 0;
        int jumlahbarang, hargabarang;
        for (int i = 0; i < jumlahbaris; i++){
            jumlahbarang = Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            hargabarang = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            grandtotal = grandtotal + (jumlahbarang * hargabarang);
        }
        txtgrandtotal.setText(String.valueOf(grandtotal));
    }
    
    public void loadData(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object []{
            txtnotransaksi.getText(),
            txtkodebarang.getText(),
            txtnamabarang.getText(),
            txthargabarang.getText(),
            txtjumlah.getText(),
            txttotal.getText()
        });
    }
    
    public void kosong(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        while (model.getRowCount()>0){
            model.removeRow(0);
        }
    }
    
    public void utama(){
            txtnotransaksi.setText("");
            txtkodebarang.setText("");
            txtnamabarang.setText("");
            txthargabarang.setText("");
            txtjumlah.setText("");
            txttotal.setText("");
            
            autonumber();
    }
    
    public void clear(){
            txtkodebarang.setText("");
            txtnamabarang.setText("");
            txthargabarang.setText("");
            txtjumlah.setText("");
            txttotal.setText("");
            
            
    }
    
    private void autonumber(){
        try{
            String sql = "select * from transaksi order by id_transaksi desc";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()){
                String NoTrans = rs.getString("id_transaksi").substring(2);
                String TR = "" + (Integer.parseInt(NoTrans)+1);
                String Nol = "";
                
                if (TR.length()==1){
                    Nol = "000";
                }else if (TR.length()==2){
                    Nol = "00";
                }else if (TR.length()==3){
                    Nol = "0";
                }else if(TR.length()==4){
                    Nol = "";
                }txtnotransaksi.setText("TR" +  Nol + TR);
            }else{
                txtnotransaksi.setText("TR0001");
            }
            
        }catch(Exception e){
            System.out.println("auto number error");
            
        }
    }
    
    public void tambahtransaksi(){
        int jumlah, harga, total;
        
        jumlah = Integer.valueOf(txtjumlah.getText());
        harga = Integer.valueOf((txthargabarang.getText()));
        total = jumlah * harga;
        
        txttotal.setText((String.valueOf(total)));
        
        loadData();
        
    }
    
    public Kasir() {
        initComponents();
//        txt_namaKasir.setText(Session.get_username());
//        txt_namaKasir.setEchoChar('*');
        
        model = new DefaultTableModel();
        
        jTable1.setModel(model);
        
        model.addColumn("No Transaksi");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jumlah");
        model.addColumn("Total");
        
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        
        txttanggal.setText(s.format(date));
        txtgrandtotal.setText("0");
        txtbayar.setText("");
        txtkembali.setText("0");
        txtkodebarang.requestFocus();
        
        utama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnbayar = new javax.swing.JButton();
        txtkodebarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txttotal = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtkembali = new javax.swing.JTextField();
        txtgrandtotal = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txtnotransaksi = new javax.swing.JTextField();
        txthargabarang = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jButton5.setText("Cetak");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 870, 180, 70));

        btntambah.setBackground(new java.awt.Color(0, 215, 255));
        btntambah.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        btntambah.setText("Tambah");
        btntambah.setBorder(null);
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 760, 180, 70));

        btnbayar.setBackground(new java.awt.Color(255, 228, 0));
        btnbayar.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        btnbayar.setText("Bayar");
        btnbayar.setBorder(null);
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 760, 180, 70));

        txtkodebarang.setBackground(new java.awt.Color(254, 234, 223));
        txtkodebarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtkodebarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtkodebarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtkodebarangMouseEntered(evt);
            }
        });
        txtkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 390, 70));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Rectangle 70.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 870, 180, 80));

        btnhapus.setBackground(new java.awt.Color(255, 30, 30));
        btnhapus.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.setBorder(null);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 870, 180, 70));

        jLabel5.setBackground(new java.awt.Color(0, 215, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Rectangle 70.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 760, 180, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 1250, 400));

        txttotal.setBackground(new java.awt.Color(237, 231, 228));
        txttotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 280, 320, 70));

        txtbayar.setBackground(new java.awt.Color(237, 231, 228));
        txtbayar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtbayar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 500, 320, 70));

        txtjumlah.setBackground(new java.awt.Color(237, 231, 228));
        txtjumlah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtjumlah.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 170, 310, 70));

        txtkembali.setBackground(new java.awt.Color(237, 231, 228));
        txtkembali.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtkembali.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 620, 320, 70));

        txtgrandtotal.setBackground(new java.awt.Color(237, 231, 228));
        txtgrandtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtgrandtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtgrandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 390, 320, 70));

        txtnamabarang.setBackground(new java.awt.Color(254, 234, 223));
        txtnamabarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnamabarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 390, 70));

        txtnotransaksi.setBackground(new java.awt.Color(254, 234, 223));
        txtnotransaksi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnotransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtnotransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(txtnotransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 390, 70));

        txthargabarang.setBackground(new java.awt.Color(254, 234, 223));
        txthargabarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txthargabarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        getContentPane().add(txthargabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, 390, 70));

        txttanggal.setBackground(new java.awt.Color(254, 234, 223));
        txttanggal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttanggal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        getContentPane().add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 390, 70));

        txt_namaKasir.setBackground(new java.awt.Color(254, 234, 223));
        txt_namaKasir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_namaKasir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        getContentPane().add(txt_namaKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 390, 70));

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });
        getContentPane().add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 390, 40));

        jLabel6.setBackground(new java.awt.Color(255, 228, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Rectangle 70.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 760, 180, 80));

        jLabel8.setBackground(new java.awt.Color(255, 30, 30));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Rectangle 70.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 870, 180, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/kasir (5).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String id_transaksi =  txtnotransaksi.getText();
        String  tanggal = txttanggal.getText();
        String grand_total = txtgrandtotal.getText();
        String bayar = txtbayar.getText();
        String kembali = txtkembali.getText();
//        String Kasir = txt_namaKasir.getText();
        String nik = txtnik.getText();
        
        
        try{
            String sql = "insert into transaksi values (?,?,?,?,?,?)";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id_transaksi);
            pst.setString(2, tanggal);
            pst.setString(3, grand_total);
            pst.setString(4, bayar);
            pst.setString(5, kembali);
            pst.setString(6, nik);
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Berhasil");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal" + e.getMessage());
        }
        
        try{
            java.sql.Connection conn = (Connection)koneksi.configDB();
            int baris = jTable1.getRowCount();
            
            for(int i = 0; i < baris; i++){
                String sql = "insert into detail_transaksi (id_transaksi, id_barang, jumlah, total_harga) values ('" + jTable1.getValueAt(i, 0) + "','"
                        + jTable1.getValueAt(i, 1) + "','" + jTable1.getValueAt(i, 4) + "','" + jTable1.getValueAt(i, 5) + "')";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.executeUpdate();
                pst.close();
                
                JOptionPane.showMessageDialog(null, "Berhasil");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal" + e.getMessage());   
        }
        clear();
        utama();
        autonumber();
        kosong();
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        model.removeRow(row);
        grandtotal();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
         // TODO add your handling code here:
         tambahtransaksi();
         grandtotal();
         utama();
         //loadData();
         clear();
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtnotransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotransaksiActionPerformed

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "select * from barang where nama_barang = '"+txtnamabarang.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
                txthargabarang.setText(rs.getString("harga_jual"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        txtjumlah.requestFocus();
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
        int jumlah, harga, total;
        
        jumlah = Integer.valueOf(txtjumlah.getText());
        harga = Integer.valueOf((txthargabarang.getText()));
        total = jumlah * harga;
        
        txttotal.setText((String.valueOf(total)));
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
        int total, bayar, kembalian;
        
        total = Integer.valueOf(txtgrandtotal.getText());
        bayar = Integer.valueOf(txtbayar.getText());
        
        if (total > bayar){
            JOptionPane.showMessageDialog(null, "Uang Tidak Cukup Untuk Melakukan Pembayaran");
        }else{
            kembalian = bayar - total;
            txtkembali.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebarangActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "select * from barang where id_barang = '"+txtkodebarang.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
                txtnamabarang.setText(rs.getString("nama_barang"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        txtnamabarang.requestFocus();
    }//GEN-LAST:event_txtkodebarangActionPerformed

    private void txtkodebarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkodebarangMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtkodebarangMouseEntered

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static final javax.swing.JTextField txt_namaKasir = new javax.swing.JTextField();
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtgrandtotal;
    private javax.swing.JTextField txthargabarang;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    public static final javax.swing.JTextField txtnik = new javax.swing.JTextField();
    private javax.swing.JTextField txtnotransaksi;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
