import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import com.barcodelib.barcode.Linear;
import com.itextpdf.text.Font;
import javax.swing.UIManager;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
public class barang extends javax.swing.JFrame {
private DefaultTableModel model;
    private void autocode(){
        try{
            Connection c=konkesiAPP.koneksi.configDB();
            Statement s=c.createStatement();
            String sql="select * from barang order by id_barang desc";
            ResultSet r=s.executeQuery(sql);
            if (r.next()){
                String kodebarang=r.getString("id_barang").substring(2);
                String KB =""+(Integer.parseInt(kodebarang)+1);
                String Nol="";
                if (KB.length()==1){
                    Nol="00"; 
                }else if (KB.length()==2){
                   Nol="0";
                }else if (KB.length()==3){
                    Nol="";}
                    txt_kodebarang.setText("KB" +Nol +KB);
            }else {
                txt_kodebarang.setText("KB001");
            }
            c.close();
            s.close();
        }catch (Exception e){
            System.out.println("autonumber error");
}
    }
    
    public void clear(){
        txt_kodebarang.setText("");
        txt_namabarang.setText("");
        txt_hargabeli.setText("");
        txt_stok.setText("");
        txt_keuntungan.setText("");
        txt_hargajual.setText("");
        txt_presentase.setText("");
    }
    public void tampilkanTabel(){
        DefaultTableModel model = new DefaultTableModel();
        
        jTable2.setModel(model);
        
        model.addColumn("kode barang");
        model.addColumn("Nama barang");
        model.addColumn("Harga beli");
        model.addColumn("Keuntungan");
        model.addColumn("Harga Jual");
        model.addColumn("Presentase");
        model.addColumn("Stok");
        
       try {
            Statement s = konkesiAPP.koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * from barang");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("keuntungan"),
                    rs.getString("harga_jual"),
                    rs.getString("presentase"),
                    rs.getString("stok"),
                });
                jTable2.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
}
}
    public barang() {
        try{
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex){
            ex.getMessage();
             
        }
        initComponents();
        
        autocode();
        tampilkanTabel();
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        txtusernamee1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_namabarang = new javax.swing.JTextField();
        txt_hargabeli = new javax.swing.JTextField();
        txt_keuntungan = new javax.swing.JTextField();
        txt_kodebarang = new javax.swing.JTextField();
        txt_hargajual = new javax.swing.JTextField();
        txt_presentase = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        jLabel2.setText("%");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 260, 40, 60));

        txt_stok.setBackground(new java.awt.Color(237, 231, 228));
        txt_stok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_stok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_stok.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_stok.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stokActionPerformed(evt);
            }
        });
        getContentPane().add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 190, 200, 50));

        txtusernamee1.setText("jLabel2");
        getContentPane().add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 120, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/cetak (1).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 373, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icon hapus.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 373, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/tambah icon.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 373, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/edit icon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 373, 50, 50));

        txt_namabarang.setBackground(new java.awt.Color(237, 231, 228));
        txt_namabarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_namabarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_namabarang.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_namabarang.setPreferredSize(new java.awt.Dimension(4, 33));
        getContentPane().add(txt_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 200, 70));

        txt_hargabeli.setBackground(new java.awt.Color(237, 231, 228));
        txt_hargabeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_hargabeli.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_hargabeli.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_hargabeli.setPreferredSize(new java.awt.Dimension(4, 33));
        getContentPane().add(txt_hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, 180, 70));

        txt_keuntungan.setBackground(new java.awt.Color(237, 231, 228));
        txt_keuntungan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_keuntungan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_keuntungan.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_keuntungan.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_keuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keuntunganActionPerformed(evt);
            }
        });
        getContentPane().add(txt_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 190, 200, 50));

        txt_kodebarang.setBackground(new java.awt.Color(237, 231, 228));
        txt_kodebarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_kodebarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_kodebarang.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_kodebarang.setPreferredSize(new java.awt.Dimension(4, 33));
        getContentPane().add(txt_kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 200, 70));

        txt_hargajual.setBackground(new java.awt.Color(237, 231, 228));
        txt_hargajual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_hargajual.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_hargajual.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_hargajual.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_hargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargajualActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 270, 200, 50));

        txt_presentase.setBackground(new java.awt.Color(237, 231, 228));
        txt_presentase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_presentase.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_presentase.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_presentase.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_presentase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_presentaseActionPerformed(evt);
            }
        });
        getContentPane().add(txt_presentase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 180, 50));

        btn_hapus.setBackground(new java.awt.Color(255, 30, 30));
        btn_hapus.setBorder(null);
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 363, 86, 67));

        btn_cetak.setBackground(new java.awt.Color(204, 204, 204));
        btn_cetak.setBorder(null);
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1786, 363, 86, 67));

        btn_edit.setBackground(new java.awt.Color(255, 228, 0));
        btn_edit.setBorder(null);
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 363, 86, 67));

        btn_tambah.setBackground(new java.awt.Color(0, 215, 255));
        btn_tambah.setBorder(null);
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 363, 86, 67));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 1440, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/barang (8).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1020));

        setSize(new java.awt.Dimension(1930, 1034));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO barang VALUES('"+txt_kodebarang.getText()+"','"+txt_namabarang.getText()+"','"
                    +txt_hargabeli.getText()+"','"+txt_hargajual.getText()+"','"+txt_stok.getText()+"','"+txt_keuntungan.getText()+"','"+txt_presentase.getText()+"')";
            java.sql.Connection conn = (Connection)konkesiAPP.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            this.setVisible(false);
            new barang().setVisible(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tampilkanTabel();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
      this.dispose();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        try{
            String sql = "UPDATE barang SET harga_beli=id_barang='"+txt_kodebarang.getText()+"', nama_barang='"+txt_namabarang.getText()+"', harga_beli='"+txt_hargabeli.getText()+"', keuntungan='"+txt_keuntungan.getText()+"', harga_jual='"+txt_hargajual.getText()
                    +"', keuntungan='"+txt_presentase.getText()+"', stok='"+txt_stok.getText()+"' WHERE id_barang='"+txt_kodebarang.getText()+"'"; 
            java.sql.Connection conn = (Connection)konkesiAPP.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            this.setVisible(false);
            new barang().setVisible(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
            tampilkanTabel();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
        try{
            String sql = "DELETE from barang where id_barang='"+txt_kodebarang.getText()+"'";
            java.sql.Connection conn = (Connection)konkesiAPP.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            tampilkanTabel();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkanTabel();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void txt_hargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargajualActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_hargajualActionPerformed

    private void txt_keuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keuntunganActionPerformed
        // TODO add your handling code here:
        String Harga_Beli = txt_hargabeli.getText();
        String Keuntungan = txt_keuntungan.getText();

        
        int Harga_Jual = Integer.parseInt(Harga_Beli) + Integer.parseInt(Keuntungan);
  
        txt_hargajual.setText("" + Harga_Jual);
        
        
    }//GEN-LAST:event_txt_keuntunganActionPerformed

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        // TODO add your handling code here:
        try{
           Linear barcode = new Linear();
        barcode.setType(Linear.CODE128A);
        barcode.setData(txt_kodebarang.getText());
        barcode.setI(11.0f);
        String fname= txt_kodebarang.getText();
        barcode.renderBarcode("src/images_barcode/" + fname + ".png"); 
        }catch (Exception e){
           JOptionPane.showMessageDialog(null,"Gagal mencetak barcode"+ e);
}
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void txt_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stokActionPerformed

    private void txt_presentaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_presentaseActionPerformed
        // TODO add your handling code here:
        String Harga_Beli = txt_hargabeli.getText();
        String Presentase = txt_presentase.getText();
        
        int Keuntungan = Integer.parseInt(Harga_Beli) * Integer.parseInt(Presentase)/100;

        txt_keuntungan.setText("" + Keuntungan);
        
        txt_keuntungan.requestFocus();
    }//GEN-LAST:event_txt_presentaseActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        String kode = model.getValueAt(i, 0).toString();
        String nama = model.getValueAt(i, 1).toString();
        String hargabeli = model.getValueAt(i, 2).toString();
        String stok = model.getValueAt(i, 6).toString();
        String keuntungan = model.getValueAt(i, 3).toString();
        String hargajual = model.getValueAt(i, 4).toString();
        String presentase = model.getValueAt(i, 5).toString();
        
        txt_kodebarang.setText(kode);
        txt_namabarang.setText(nama);
        txt_hargabeli.setText(hargabeli);
        txt_stok.setText(stok);
        txt_keuntungan.setText(keuntungan);
        txt_hargajual.setText(hargajual);
        txt_presentase.setText(presentase);
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_hargajual;
    private javax.swing.JTextField txt_keuntungan;
    private javax.swing.JTextField txt_kodebarang;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_presentase;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables
}
