import konkesiAPP.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
public class Forgot_Password extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_Password
     */
    public Forgot_Password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusername = new javax.swing.JTextField();
        txtquestion = new javax.swing.JTextField();
        txtanswer = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setBackground(new java.awt.Color(237, 231, 228));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 730, 60));

        txtquestion.setBackground(new java.awt.Color(237, 231, 228));
        txtquestion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtquestion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtquestion.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        getContentPane().add(txtquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 730, 60));

        txtanswer.setBackground(new java.awt.Color(237, 231, 228));
        txtanswer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 730, 60));

        txtpassword.setBackground(new java.awt.Color(237, 231, 228));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 730, 60));

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        btnback.setForeground(new java.awt.Color(241, 175, 9));
        btnback.setText("BACK");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 780, 220, 70));

        jButton2.setBackground(new java.awt.Color(241, 175, 9));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 780, 220, 70));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 220, 60));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 240, 200, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/forgot psswrd (4).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = txtusername.getText();
        String newPassword = txtpassword.getText();
        String question = txtquestion.getText();
        String answer = txtanswer.getText();
        
       try{
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pakanstore","root","123");
            //Statement st = con.createStatement();
            //ResultSet rs = st.executeQuery("select * from user where username ='"+username+"' and answer='"+answer+"'");
            
           String sql = "SELECT * FROM user WHERE username = '"+txtusername.getText()+"' and answer='"+answer+"'";
           java.sql.Connection conn = (Connection)koneksi.configDB();
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
           java.sql.ResultSet rs = pst.executeQuery(sql);
           
           if(rs.next()){
              pst.executeUpdate("update user set password='"+newPassword+"' where username='"+username+"' and answer='"+answer+"'");
              JOptionPane.showMessageDialog(null, "Your Password is Succefully Update");
              setVisible(false);
              new LoginAPP().setVisible(true);
           }
           else
              JOptionPane.showMessageDialog(null, "Please Write Correct Username or Answer*");
          
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "Erorr In Connection");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        setVisible(false);
        new LoginAPP().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      String username = txtusername.getText();
        try{
           // Class.forName("com.mysql.jdbc.Driver");
            //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pakanstore","root","123");
            //Statement st = con.createStatement();
            //ResultSet rs = st.executeQuery("select question from user where username ='"+username+"'");
           String sql = "SELECT * FROM user WHERE username = '"+txtusername.getText()+"'";
           java.sql.Connection conn = (Connection)koneksi.configDB();
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
           java.sql.ResultSet rs = pst.executeQuery(sql);
           
           if(rs.next()){
               txtquestion.setText(rs.getString(5));
           }
           else
               JOptionPane.showMessageDialog(null, "Please write correct Username");
           conn.close();
           rs.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "Error In Connection");
        }
              
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtquestion;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
