/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Pembelian extends javax.swing.JFrame {

    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusernamee1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtid1 = new javax.swing.JTextField();
        txtid3 = new javax.swing.JTextField();
        txtid4 = new javax.swing.JTextField();
        txtid5 = new javax.swing.JTextField();
        txtid6 = new javax.swing.JTextField();
        txtid7 = new javax.swing.JTextField();
        txtid8 = new javax.swing.JTextField();
        txtid10 = new javax.swing.JTextField();
        txtid9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1930, 1020));
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1754, 212, 110, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Tambah Pemasokan.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 468, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icon hapus.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 460, 50, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/tambah icon.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 50, 50));

        txtusernamee1.setText("jLabel2");
        getContentPane().add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 120, 110, 30));

        jButton6.setBackground(new java.awt.Color(100, 234, 78));
        jButton6.setForeground(new java.awt.Color(100, 234, 78));
        jButton6.setBorder(null);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 457, 170, 67));

        jButton5.setBackground(new java.awt.Color(255, 30, 30));
        jButton5.setForeground(new java.awt.Color(255, 30, 30));
        jButton5.setBorder(null);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 457, 86, 67));

        jButton4.setBackground(new java.awt.Color(0, 215, 255));
        jButton4.setForeground(new java.awt.Color(0, 215, 255));
        jButton4.setBorder(null);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 457, 86, 67));

        txtid.setBackground(new java.awt.Color(237, 231, 228));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 310, 60));

        txtid1.setBackground(new java.awt.Color(237, 231, 228));
        txtid1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid1.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid1.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 310, 60));

        txtid3.setBackground(new java.awt.Color(237, 231, 228));
        txtid3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid3.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid3.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 260, 60));

        txtid4.setBackground(new java.awt.Color(237, 231, 228));
        txtid4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid4.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid4.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 310, 60));

        txtid5.setBackground(new java.awt.Color(237, 231, 228));
        txtid5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid5.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid5.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 350, 260, 60));

        txtid6.setBackground(new java.awt.Color(237, 231, 228));
        txtid6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid6.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid6.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 190, 120, 60));

        txtid7.setBackground(new java.awt.Color(237, 231, 228));
        txtid7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid7.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid7.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 280, 260, 60));

        txtid8.setBackground(new java.awt.Color(237, 231, 228));
        txtid8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid8.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid8.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid8ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 350, 260, 60));

        txtid10.setBackground(new java.awt.Color(237, 231, 228));
        txtid10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid10.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid10.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid10ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 270, 260, 60));

        txtid9.setBackground(new java.awt.Color(237, 231, 228));
        txtid9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid9.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid9.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid9ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 440, 210, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/pembelian (7).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid3ActionPerformed

    private void txtid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid4ActionPerformed

    private void txtid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid5ActionPerformed

    private void txtid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid6ActionPerformed

    private void txtid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid7ActionPerformed

    private void txtid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid8ActionPerformed

    private void txtid9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid9ActionPerformed

    private void txtid10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtid10;
    private javax.swing.JTextField txtid3;
    private javax.swing.JTextField txtid4;
    private javax.swing.JTextField txtid5;
    private javax.swing.JTextField txtid6;
    private javax.swing.JTextField txtid7;
    private javax.swing.JTextField txtid8;
    private javax.swing.JTextField txtid9;
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables
}
