
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Pengaturan extends javax.swing.JFrame {
     public void ShowData(){
        DefaultTableModel model = new DefaultTableModel();
        
        jTable2.setModel(model);
        model.addColumn("NIK");
        model.addColumn("Nama Lengkap");
        model.addColumn("Alamat");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Jabatan");
        model.addColumn("Question");
        model.addColumn("Answer");
        
        try{
        Statement s = konkesiAPP.koneksi.configDB().createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM user");
        
        while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("nik"),
                    rs.getString("nama_lengkap"),
                    rs.getString("alamat"),
                    rs.getString("username"),
                    rs.getString("password"),
                    rs.getString("jabatan"),
                    rs.getString("question"),
                    rs.getString("answer"),
                    
                });
                jTable2.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
    }   
        
    }
     
     public void clear(){
        txtnik.setText("");
        txtnamalengkap.setText("");
        txtalamat.setText("");
        txtusername.setText("");
        txtpassword.setText("");
        txtquestion.setText("");
        txtanswer.setText("");
       
    }

    /**
     * Creates new form Pengaturan
     */
    public Pengaturan() {
        initComponents();
        ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_tmbh = new javax.swing.JButton();
        txtnik = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtquestion = new javax.swing.JTextField();
        txtanswer = new javax.swing.JTextField();
        txtnamalengkap = new javax.swing.JTextField();
        rAdmin = new javax.swing.JRadioButton();
        rKaryawan = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 880, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icon hapus.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 920, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/edit icon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1533, 920, 50, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/tambah icon.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 920, 50, 50));

        btn_hapus.setBackground(new java.awt.Color(255, 30, 30));
        btn_hapus.setBorder(null);
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1783, 908, 86, 67));

        btn_edit.setBackground(new java.awt.Color(255, 228, 0));
        btn_edit.setBorder(null);
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1514, 908, 86, 67));

        btn_tmbh.setBackground(new java.awt.Color(0, 215, 255));
        btn_tmbh.setForeground(new java.awt.Color(0, 215, 255));
        btn_tmbh.setBorder(null);
        btn_tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbhActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tmbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1387, 907, 86, 67));

        txtnik.setBackground(new java.awt.Color(237, 231, 228));
        txtnik.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnik.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtnik.setMinimumSize(new java.awt.Dimension(4, 33));
        txtnik.setPreferredSize(new java.awt.Dimension(4, 33));
        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });
        getContentPane().add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 380, 310, 40));

        txtalamat.setBackground(new java.awt.Color(237, 231, 228));
        txtalamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtalamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtalamat.setMinimumSize(new java.awt.Dimension(4, 33));
        txtalamat.setPreferredSize(new java.awt.Dimension(4, 33));
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 450, 310, 40));

        txtusername.setBackground(new java.awt.Color(237, 231, 228));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtusername.setMinimumSize(new java.awt.Dimension(4, 33));
        txtusername.setPreferredSize(new java.awt.Dimension(4, 33));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 510, 310, 40));

        txtpassword.setBackground(new java.awt.Color(237, 231, 228));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtpassword.setMinimumSize(new java.awt.Dimension(4, 33));
        txtpassword.setPreferredSize(new java.awt.Dimension(4, 33));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 590, 310, 40));

        txtquestion.setBackground(new java.awt.Color(237, 231, 228));
        txtquestion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtquestion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtquestion.setMinimumSize(new java.awt.Dimension(4, 33));
        txtquestion.setPreferredSize(new java.awt.Dimension(4, 33));
        txtquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquestionActionPerformed(evt);
            }
        });
        getContentPane().add(txtquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 660, 310, 40));

        txtanswer.setBackground(new java.awt.Color(237, 231, 228));
        txtanswer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtanswer.setMinimumSize(new java.awt.Dimension(4, 33));
        txtanswer.setPreferredSize(new java.awt.Dimension(4, 33));
        txtanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 720, 310, 40));

        txtnamalengkap.setBackground(new java.awt.Color(237, 231, 228));
        txtnamalengkap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnamalengkap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtnamalengkap.setMinimumSize(new java.awt.Dimension(4, 33));
        txtnamalengkap.setPreferredSize(new java.awt.Dimension(4, 33));
        txtnamalengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamalengkapActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 310, 310, 40));

        rAdmin.setText("Admin");
        getContentPane().add(rAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 800, -1, -1));

        rKaryawan.setText("Karyawan");
        getContentPane().add(rKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 800, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Pengaturan (6).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquestionActionPerformed

    private void txtanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerActionPerformed

    private void txtnamalengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamalengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamalengkapActionPerformed

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbhActionPerformed
        // TODO add your handling code here:
        String jk = null;
        if(rAdmin.isSelected()){
            jk = "Admin";
        }else if(rKaryawan.isSelected()){
            jk = "Karyawan";
        }
        try{
            String sql = "INSERT INTO user(nik, nama_lengkap , alamat, username, password, jabatan, question, answer) VALUES ('"+txtnik.getText()+"','"+txtnamalengkap.getText()
                    +"','"+txtalamat.getText()+"','"+txtusername.getText()+"','"+txtpassword.getText()
                    +"','"+jk+"','"+txtquestion.getText()+"','"+txtanswer.getText()+"')";
            java.sql.Connection conn = (Connection)konkesiAPP.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            ShowData();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR \n" +e.getMessage());
        }
          
    }//GEN-LAST:event_btn_tmbhActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        String nik = model.getValueAt(i, 0).toString();
        String nama = model.getValueAt(i, 1).toString();
        String alamat = model.getValueAt(i, 2).toString();
        String username = model.getValueAt(i, 3).toString();
        String password = model.getValueAt(i, 4).toString();
        String question = model.getValueAt(i, 6).toString();
        String answer = model.getValueAt(i, 7).toString();
        
        txtnik.setText(nik);
        txtnamalengkap.setText(nama);
        txtalamat.setText(alamat);
        txtusername.setText(username);
        txtpassword.setText(password);
        txtquestion.setText(question);
        txtanswer.setText(answer);
    }//GEN-LAST:event_jTable2MouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String jk = null;
        if(rAdmin.isSelected()){
            jk = "Admin";
        }else if(rKaryawan.isSelected()){
            jk = "Karyawan";
        }
        try{
            String sql = "UPDATE user SET nama_lengkap='"+txtnamalengkap.getText()+"', alamat='"+txtalamat.getText()+"', username='"
                    +txtusername.getText()+"', password='"+txtpassword.getText()
                    +"', jabatan='"+ jk +"', question='"+txtquestion.getText()+"', answer='"+txtanswer.getText()+"' WHERE nik='"+txtnik.getText()+"'"; 
            java.sql.Connection conn = (Connection)konkesiAPP.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
            ShowData();
            clear();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE from user where nik='"+txtnik.getText()+"'";
            java.sql.Connection conn = (Connection)konkesiAPP.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            ShowData();
            clear();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengaturan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tmbh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rAdmin;
    private javax.swing.JRadioButton rKaryawan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JTextField txtnamalengkap;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtquestion;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
