/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan
     */
    public Penjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusernamee1 = new javax.swing.JLabel();
        txtid4 = new javax.swing.JTextField();
        txtid5 = new javax.swing.JTextField();
        txtid6 = new javax.swing.JTextField();
        txtid7 = new javax.swing.JTextField();
        txtid8 = new javax.swing.JTextField();
        txtid9 = new javax.swing.JTextField();
        txtid10 = new javax.swing.JTextField();
        txtid11 = new javax.swing.JTextField();
        txtid12 = new javax.swing.JTextField();
        txtid13 = new javax.swing.JTextField();
        txtid14 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusernamee1.setText("jLabel2");
        getContentPane().add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 120, 110, 30));

        txtid4.setBackground(new java.awt.Color(237, 231, 228));
        txtid4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid4.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid4.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 310, 60));

        txtid5.setBackground(new java.awt.Color(237, 231, 228));
        txtid5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid5.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid5.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 310, 60));

        txtid6.setBackground(new java.awt.Color(237, 231, 228));
        txtid6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid6.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid6.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 280, 60));

        txtid7.setBackground(new java.awt.Color(237, 231, 228));
        txtid7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid7.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid7.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 180, 270, 60));

        txtid8.setBackground(new java.awt.Color(237, 231, 228));
        txtid8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid8.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid8.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid8ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 340, 280, 60));

        txtid9.setBackground(new java.awt.Color(237, 231, 228));
        txtid9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid9.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid9.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid9ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 310, 60));

        txtid10.setBackground(new java.awt.Color(237, 231, 228));
        txtid10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid10.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid10.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid10ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 580, 220, 60));

        txtid11.setBackground(new java.awt.Color(237, 231, 228));
        txtid11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid11.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid11.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid11ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, 280, 60));

        txtid12.setBackground(new java.awt.Color(237, 231, 228));
        txtid12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid12.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid12.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid12ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 660, 220, 60));

        txtid13.setBackground(new java.awt.Color(237, 231, 228));
        txtid13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid13.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid13.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid13ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 740, 220, 60));

        txtid14.setBackground(new java.awt.Color(237, 231, 228));
        txtid14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid14.setMinimumSize(new java.awt.Dimension(4, 33));
        txtid14.setPreferredSize(new java.awt.Dimension(4, 33));
        txtid14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid14ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 260, 270, 60));

        jButton4.setBackground(new java.awt.Color(255, 30, 30));
        jButton4.setText("jButton1");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1717, 452, 140, 70));

        jButton5.setBackground(new java.awt.Color(198, 198, 198));
        jButton5.setText("jButton1");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1508, 839, 140, 70));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setText("jButton1");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1717, 839, 140, 70));

        jButton3.setBackground(new java.awt.Color(0, 215, 255));
        jButton3.setText("jButton1");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1507, 452, 140, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/penjualan (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid4ActionPerformed

    private void txtid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid5ActionPerformed

    private void txtid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid6ActionPerformed

    private void txtid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid7ActionPerformed

    private void txtid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid8ActionPerformed

    private void txtid9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid9ActionPerformed

    private void txtid10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid10ActionPerformed

    private void txtid11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid11ActionPerformed

    private void txtid12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid12ActionPerformed

    private void txtid13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid13ActionPerformed

    private void txtid14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtid10;
    private javax.swing.JTextField txtid11;
    private javax.swing.JTextField txtid12;
    private javax.swing.JTextField txtid13;
    private javax.swing.JTextField txtid14;
    private javax.swing.JTextField txtid4;
    private javax.swing.JTextField txtid5;
    private javax.swing.JTextField txtid6;
    private javax.swing.JTextField txtid7;
    private javax.swing.JTextField txtid8;
    private javax.swing.JTextField txtid9;
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables
}
